### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lex111** [lex111/es6generators#3]
- [x] basic/README.md @katienazarova 
- [x] basic/basic_generators.md @katienazarova 
- [x] basic/pass_values_to_next.md @lex111 
- [x] basic/return_in_generators.md @lex111
- [x] basic/iterators_generators.md @lex111
- [x] advanced/README.md @katienazarova 
- [x] advanced/generator_arguments.md @katienazarova 
- [x] advanced/return_method.md @katienazarova
- [x] advanced/throw_method.md @katienazarova
- [x] advanced/yield_star.md @katienazarova
- [x] advanced/nested_yield.md @katienazarova
- [x] advanced/co.md @katienazarova
- [x] advanced/regenerator.md @katienazarova
- [x] realworld_usages/README.md @lex111 
- [x] realworld_usages/koa/README.md @lex111 
- [x] realworld_usages/koa/koa_basics.md @lex111 
- [x] realworld_usages/koa/koa_compose.md @lex111 
- [x] realworld_usages/babel/README.md @lex111 
- [x] realworld_usages/babel/async_await.md @lex111 
- [x] usage_scenarios/README.md @katienazarova
- [x] usage_scenarios/sequence_generation.md @katienazarova
- [x] usage_scenarios/task_queue.md @katienazarova
